#!/usr/bin/env bash
set -euo pipefail

echo ""
echo "=== Brain Command Center — Cloud Sync Setup ==="
echo ""

GH_CMD="$HOME/bin/gh"
if [ ! -f "$GH_CMD" ]; then GH_CMD="gh"; fi
if ! command -v "$GH_CMD" &>/dev/null; then
  echo "ERROR: GitHub CLI (gh) not found. Run: ~/bin/gh auth login"
  exit 1
fi

if ! "$GH_CMD" auth status &>/dev/null; then
  echo "ERROR: Not logged in. Run: $GH_CMD auth login"
  exit 1
fi

USERNAME=$("$GH_CMD" api /user --jq '.login' 2>/dev/null || echo "unknown")
echo "Logged in as: $USERNAME"

echo "Creating private sync gist..."
GIST_JSON=$("$GH_CMD" api /gists -X POST \
  -f "description=Brain Command Center sync — do not delete" \
  -f "public=false" \
  -f "files[brain-command-center-data.json][content]={\"_syncedAt\":0}" 2>&1)

GIST_ID=$(echo "$GIST_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin)['id'])" 2>/dev/null)
if [ -z "$GIST_ID" ]; then
  echo "ERROR: Could not create Gist. Output:"
  echo "$GIST_JSON"
  exit 1
fi
echo "Gist created: $GIST_ID"

TOKEN=$("$GH_CMD" auth token 2>/dev/null || echo "")
if [ -z "$TOKEN" ]; then
  echo "ERROR: Could not get auth token."
  exit 1
fi

# Verify token can access gists
TEST=$("$GH_CMD" api "/gists/$GIST_ID" --jq '.id' 2>/dev/null || echo "")
if [ "$TEST" != "$GIST_ID" ]; then
  echo "WARNING: Token may not have gist scope. Sync might not work."
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cat > "$SCRIPT_DIR/sync-config.js" <<JS
// Auto-generated by setup-sync.sh — do not edit
window.SYNC_GIST_ID='${GIST_ID}';
window.SYNC_TOKEN='${TOKEN}';
JS

echo "Wrote sync-config.js"

PAIR_CODE="BCC:${GIST_ID}:${TOKEN}"
echo ""
echo "========================================================"
echo "  DESKTOP: Done! Open index.html — sync is automatic."
echo ""
echo "  PHONE: Copy the code below and paste it into the app:"
echo ""
echo "  $PAIR_CODE"
echo ""
echo "  On your phone: tap the 🔗 icon → paste this code."
echo "========================================================"
echo ""
